# Generated by Django 5.1 on 2024-09-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
